packages:
  - packages/app
  - packages/design
  - packages/sdk
  - packages/discord-bridge
  - packages/tsconfig

onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - cbor-extract
  - core-js
  - esbuild
  - node

patchedDependencies:
  "@grafana/faro-core": patches/@grafana__faro-core.patch
  "@grafana/faro-web-sdk": patches/@grafana__faro-web-sdk.patch
  "@discordeno/gateway": patches/@discordeno__gateway.patch
