packages:
  - packages/*
ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - cbor-extract
  - core-js
  - esbuild
  - node
patchedDependencies:
  '@discordjs/util': patches/@discordjs__util.patch
