packages:
  - packages/app
  - packages/design
  - packages/sdk
  - packages/discord-bridge
  - packages/tsconfig

onlyBuiltDependencies: '@parcel/watcher'

patchedDependencies:
  '@discordeno/gateway': patches/@discordeno__gateway.patch
  '@grafana/faro-core': patches/@grafana__faro-core.patch
  '@grafana/faro-web-sdk': patches/@grafana__faro-web-sdk.patch
