name: Pull Request Preview

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: |
          pnpm i
          pnpm run build-web-app
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: roomy-space
          root: packages/app/build
          entrypoint: https://deno.land/std/http/file_server.ts